backend/hospital/front/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = "front"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('doctor/<int:pk>/', views.doctor, name='doctor'),
    path('disease/<int:pk>/', views.disease, name='disease'),
    path('doctor/book/', views.booking, name='booking'),
    path('doctor/lists/', views.list, name='list'),
    path('news/<int:pk>/', views.news, name='news'),
    path('events/<int:pk>/', views.events, name='events'),
    path('doctor/book/confirm', views.bookingConfirm, name="bookingConfirm"),
    path('doctor/recomment/<int:id>', views.recommend, name="recommend"),
    path("doctor/<int:id>/review",views.review, name="review"),
    path("news-and-events/", views.blogs, name="blogs"),
    path("news/", views.all_news, name="all_news"),
    path("events/", views.all_events, name="all_events"),
    path("about-us/", views.about, name="about")
]

backend/hospital/hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('front.urls')),
    path('dashboard/', admin.site.urls),
    path('doc/',include('doctor.urls')),
    path('admin/', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/hospital/front/models.py
from django.db import models

# Create your models here.

backend/hospital/front/views.py
from django.shortcuts import render,get_object_or_404
from disease.models import Disease, Doctor
from doctor.models import Service, Doctor, Booking, Type, Review
from blogs.models import Blogs
from django.db.models import Q
from company.models import Company
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.http import HttpResponseRedirect




def index(request):
    diseases = Disease.objects.filter(status="1")
    news = Blogs.objects.filter(status="1", types="1")[:10]
    events = Blogs.objects.filter(status="1", types="0")[:10]
    doctors = Doctor.objects.filter(status="1")
    company = Company.objects.all()
    t = Type.objects.order_by("-counter").all()[0]
    return render(request, 'front/index.html', {"t":t,"diseases":diseases,"news":news, "events":events, "doctors":doctors, "company":company})

def recommend(request, id):
    doctor = Doctor.objects.filter(type__id=id)
    return render(request, "front/detail/doctorsList.html", {"doctor":doctor})


def search(request):
    doctor = Doctor.objects.filter(name__istartswith=request.POST['name'])[0]
    if doctor:
        return render(request, "front/detail/doctor.html", {'doctor': doctor})
    else:
        return render(request, "front/detail/doctor.html", {'doctor': doctor})


def doctor(request, pk):
    doctor = get_object_or_404(Doctor, pk=pk)
    return render(request, "front/detail/doctor.html", {'doctor': doctor})


def news(request, pk):
    news = get_object_or_404(Blogs, pk=pk)
    news_more = Blogs.objects.filter(status=1, types=1).exclude(pk=pk)
    return render(request, "front/detail/news.html", {'news': news, 'news_more':news_more})


def events(request, pk):
    events = get_object_or_404(Blogs, pk=pk)
    events_more = Blogs.objects.filter(status=1, types=0).exclude(pk=pk)
    return render(request, "front/detail/events.html", {'events': events, 'events_more':events_more})


def list(request):
    doctor = Doctor.objects.filter(status=1).order_by("-id")
    return render(request, "front/detail/doctorsList.html", {'doctor': doctor})


def disease(request, pk):
    disease = Disease.objects.get(pk=pk)
    disease_name = disease.name
    blogs = Blogs.objects.filter(title__istartswith=disease_name)
    return render(request, "front/detail/disease.html", {"disease":disease,"blogs":blogs})
    
    
def booking(request):
    date = request.POST["dated"]
    time = request.POST["timed"]
    dr = Doctor.objects.filter(pk=request.POST["doctor"])[0]
    services = Service.objects.filter(pk__in=request.POST.getlist('visit'))
    total=0
    for i in services:
        total+=int(i.price)
    return render(request, "front/booking/booking.html", {"date":date, "time": time,"total":total, "dr":dr,"services":services})


def bookingConfirm(request):
    fn = request.POST['fn']
    ln = request.POST['ln']
    email = request.POST['email']
    phone = request.POST['phone']
    location = request.POST['location']
    street1  = request.POST['street1']
    street2  = request.POST['street2']
    a = request.POST.getlist('service')
    services = ', '.join(a)
    dr = request.POST['doctor']
    city  = request.POST['city']
    state  = request.POST['state']
    postal  = request.POST['postal']


    book = Booking.objects.create(service=services,fn=fn,ln=ln,email=email,phone=phone,location=location,street1=street1,street2=street2,city=city, state=state, postal=postal)
    book.save()

    doc = Doctor.objects.get(pk=dr)
    a= doc.type.all()[0]
    t = Type.objects.filter(id=a.id)[0]
    t.counter = str(int(t.counter)+1)
    t.save()
    book.doctor.add(doc)
    return render(request,"front/booking/confirm.html",{"a":t})


def review(request, id):
    if request.method == 'POST':
        rate = request.POST.get('rate')
        title = request.POST['title']
        re = request.POST['re']
        doc = Doctor.objects.filter(id=id)[0]
        review = Review.objects.create(rate=rate,title=title,rev=re)
        review.save()
        review.doctor.add(doc)
        messages.success(request, "Review send. It will be published once the doctor accepts it.")
        return HttpResponseRedirect('/doctor/%d' % int(id))
    else:
        doctor = Doctor.objects.filter(id=id)[0]
        return render(request, "front/detail/review.html", {"doctor":doctor})    


def blogs(request):
    news = Blogs.objects.filter(status=1, types=1)[:3]
    events = Blogs.objects.filter(status=1, types=0)[:3]
    return render(request, "front/detail/blogs.html", {'news': news, 'events':events})


def all_news(request):
    news = Blogs.objects.filter(status=1, types=1)
    return render(request, "front/detail/allnews.html", {"news":news})

def all_events(request):
    events = Blogs.objects.filter(status=1, types=0)
    return render(request, "front/detail/allevent.html", {"events":events})


def about(request):
    return render(request, "front/detail/about.html")

backend/hospital/front/templates/front/index.html
{% extends 'front/master.html' %}

{% block content %}
<main>
{% load staticfiles %}
		<div class="hero_home version_1">
			<div class="content">
				<h3>Find a Doctor!</h3>
				<p>
					Ridiculus sociosqu cursus neque cursus curae ante scelerisque vehicula.
				</p>
				{% include 'front/forms/doctorSearch.html' %}
			</div>
		</div>
        <div class="bg_color_1">
			<div class="container margin_120_95">
				<div class="main_title">
					<h2>Viral Diseases</h2>
					<p>Latests News from the desk of Admin</p>
				</div>
				<div id="" class="container">
                    {% for disease in diseases %}
                        {% if forloop.counter|divisibleby:"3" or forloop.first %}
                            <div class="row">
                        {% endif %}
                            <div class="col-md-4">
                                <div class="card text-white   wow wobble {% if disease.level == '1' %} bg-danger {% elif disease.level == '2'%} bg-warning {% else %} bg-success {% endif %}  mb-3" style="width: 20rem;">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ disease.name }}</h5>
                                        <p class="card-text">Found: 
                                            {% if disease.found == 'o' %}
                                                Outsite Kathmandu
                                            {% elif disease.found == 'w' %}
                                                Whole Nepal
                                            {% else %}
                                                Inside Kathmandu
                                            {% endif %}
                                        </p>
                                        <p class="card-text">Type: 
                                         {% if disease.level == '1' %} 
                                            Danger
                                         {% elif disease.level == '2'%} 
                                            Mid-Range 
                                         {% else %} 
                                            Normal 
                                         {% endif %}
                                        
                                        </p>
                                        <a href="{% url 'front:disease' disease.pk %}" class="btn btn-primary btn-sm" style="margin-bottom:5%">Go somewhere</a>
                                    </div>
                                </div>
                            </div>
                        {% if forloop.counter|divisibleby:"3" or forloop.counter1 %}
                          </div>
                        {% endif %}
                    {% endfor %}
				</div>
				<!-- /carousel -->
			</div>
			<!-- /container -->
		</div>
		<!-- /Hero -->
		<div class="container margin_120_95" style="background-color:white;border-radius:20%;box-shadow:0px 0px 20px 2px #7777;">
			<div class="main_title wow fadeInDown">
				<h2>People have visited <span style="color:gold;font-weight:bold;">{{t.name}}</span> Doctor mostly</h2>
				<p>It is all based on <u style="color:gold;font-weight:bold;">User Experience</u> and <u style="color:gold;font-weight:bold;">Recommended</u> for you.	</p>
			</div>
			<div class="row add_bottom_30">
				<div class="col-lg-4 ">
					
				</div>
				<div class="col-lg-4 text-center wow fadeInRight">
					<a href="{% url 'front:recommend' t.id %}">
					<button class="btn btn-warning">Find {{t.name}} Doctor</button>
					</a>
				</div>
				<div class="col-lg-4 ">
					
				</div>
			</div>
		</div>
		<!-- /Hero -->
		<div class="container margin_120_95">
			<div class="main_title">
				<h2>Discover the <strong>online</strong> appointment!</h2>
				<p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie. Sed ad debet scaevola, ne mel.</p>
			</div>
			<div class="row add_bottom_30">
				<div class="col-lg-4 ">
					<div class="box_feat" id="icon_1">
						<span></span>
						<h3 class="wow fadeInLeft">Find a Doctor</h3>
						<p class="wow fadeInLeft">Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie.</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="box_feat" id="icon_2">
						<span></span>
						<h3 class="wow fadeInLeft">View profile</h3>
						<p class="wow fadeInLeft">Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie.</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="box_feat" id="icon_3">
						<h3 class="wow fadeInLeft">Book a visit</h3>
						<p class="wow fadeInLeft">Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie.</p>
					</div>
				</div>
			</div>
			<!-- /row -->
			<p class="text-center"><a href="{% url 'front:list' %}" class="btn_1 medium wow bounce">Find Doctor</a></p>
		</div>
		<!-- /container -->
		<div class="bg_color_1">
			<div class="container margin_120_95">
				<div class="main_title">
					<h2>Most Viewed doctors</h2>
					<p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri.</p>
				</div>
				<div id="reccomended" class="owl-carousel owl-theme">
					{% for doctor in doctors %}
						<div class="item">
							<a href="{% url 'front:doctor' doctor.pk %}">
								<div class="views"><i class="icon-eye-7"></i>140</div>
								<div class="title">
									<h4>Dr. {{doctor.name}}<em>
									{% for type in doctor.type.all %}
										{{type}}
										
									{%endfor%}
									</em></h4>
								</div><img src="{{doctor.image.url}}" alt=""/>
							</a>
						</div>
					{% endfor %}
				</div>
				<!-- /carousel -->
			</div>
			<!-- /container -->
		</div>
		<!-- /white_bg -->
		<div class="container margin_120_95">
			<div class="main_title">
				<h2>News and Events</h2>
				<p></p>
			</div>
			<div class="row justify-content-center">
				<div class="col-xl-4 col-lg-5 col-md-6">
					<div class="list_home">
						<div class="list_title">
							<i class="icon_pin_alt"></i>
							<h3>News</h3>
						</div>
						<ul>
						{% for news in news %}
								<li class="wow fadeInDown"><a href="{% url 'front:news' news.pk %}"><strong>{{forloop.counter}}</strong>{{news.title}}</a></li>
						{% endfor %}
						</ul>
					</div>
				</div>
				<div class="col-xl-4 col-lg-5 col-md-6">
					<div class="list_home">
						<div class="list_title">
							<i class="icon_archive_alt"></i>
							<h3>Events</h3>
						</div>
						<ul>
							{% for events in events %}
									<li class="wow fadeInDown"><a href="{% url 'front:events' events.pk %}"><strong>{{forloop.counter}}</strong>{{ events.title }}</a></li>									
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
		<div id="app_section">
			<div class="container">
				<div class="row justify-content-around">
					<div class="col-md-5">
						<p><img src="{% static 'frontend/img/app_img.svg' %}" alt="" class="img-fluid" width="500" height="433"></p>
					</div>
					<div class="col-md-6">
						<small>Application</small>
						<h3>Download <strong>Bio Hospital App</strong> Now!</h3>
						<p class="lead">Tota omittantur necessitatibus mei ei. Quo paulo perfecto eu, errem percipit ponderum no eos. Has eu mazim sensibus. Ad nonumes dissentiunt qui, ei menandri electram eos. Nam iisque consequuntur cu.</p>
						<div class="app_buttons wow" data-wow-offset="100">
							<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.1 85.9" style="enable-background:new 0 0 43.1 85.9;" xml:space="preserve">
							<path stroke-linecap="round" stroke-linejoin="round" class="st0 draw-arrow" d="M11.3,2.5c-5.8,5-8.7,12.7-9,20.3s2,15.1,5.3,22c6.7,14,18,25.8,31.7,33.1" />
							<path stroke-linecap="round" stroke-linejoin="round" class="draw-arrow tail-1" d="M40.6,78.1C39,71.3,37.2,64.6,35.2,58" />
							<path stroke-linecap="round" stroke-linejoin="round" class="draw-arrow tail-2" d="M39.8,78.5c-7.2,1.7-14.3,3.3-21.5,4.9" />
						</svg>
							<a href="#0" class="fadeIn"><img src="{% static 'frontend/img/apple_app.png' %}" alt="" width="150" height="50" data-retina="true"></a>
							<a href="#0" class="fadeIn"><img src="{% static 'frontend/img/google_play_app.png' %}" alt="" width="150" height="50" data-retina="true"></a>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /app_section -->
	</main>
{% endblock  %}

backend/hospital/front/templates/front/master.html
{% include 'front/partials/header.html' %}
{% include 'front/partials/navigation.html' %}
{% block content%}

{% endblock  %}
{% include 'front/partials/footer.html' %}