backend/hospital/doctor/urls.py
from rest_framework import routers
from .api import DoctorViewSet
from blogs.api import BlogViewSet
from disease.api import DiseaseViewSet
from company.api import CompanyViewSet

router = routers.DefaultRouter()
router.register('api/doctor', DoctorViewSet, 'doctor')
router.register('api/blog', BlogViewSet, 'blog')
router.register('api/disease', DiseaseViewSet, 'disease')
router.register('api/company', CompanyViewSet, 'company-details')

urlpatterns = router.urls

backend/hospital/front/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = "front"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('doctor/<int:pk>/', views.doctor, name='doctor'),
    path('disease/<int:pk>/', views.disease, name='disease'),
    path('doctor/book/', views.booking, name='booking'),
    path('doctor/lists/', views.list, name='list'),
    path('news/<int:pk>/', views.news, name='news'),
    path('events/<int:pk>/', views.events, name='events'),
    path('doctor/book/confirm', views.bookingConfirm, name="bookingConfirm"),
    path('doctor/recomment/<int:id>', views.recommend, name="recommend"),
    path("doctor/<int:id>/review",views.review, name="review"),
    path("news-and-events/", views.blogs, name="blogs"),
    path("news/", views.all_news, name="all_news"),
    path("events/", views.all_events, name="all_events"),
    path("about-us/", views.about, name="about")
]

backend/hospital/hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('front.urls')),
    path('dashboard/', admin.site.urls),
    path('doc/',include('doctor.urls')),
    path('admin/', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/hospital/blogs/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

# Create your models here.

status_choice = (
    ('1', 'Publish'),
    ('0', 'Unpublished'),
)

type_choice = (
    ('1', 'News'),
    ('0', 'Events'),
)

class Blogs(models.Model):
    title = models.CharField(max_length=300, null=False, blank = False)
    intro = models.CharField(max_length=200,null=False, blank = False)
    description = models.CharField(max_length = 1000, null=False, blank = False)
    image = models.FileField(verbose_name="Blogs Image")
    status = models.CharField(max_length=1, choices=status_choice, null=False, blank = False)
    types = models.CharField(max_length=1, choices=type_choice, null=False, blank = False)
    created_at = models.DateTimeField(default=timezone.now)

    def publish(self):
        self.status = 1
        self.save()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
            return reverse('dashboard:blogs')

backend/hospital/disease/models.py
from django.db import models
from doctor.models import Doctor
from django.utils import timezone
from django.urls import reverse



# Create your models here.
found_choice = (
    ('i', 'Inside KTM Valley'),
    ('o', 'Outside KTM Valley'),
    ('w','Whole Nepal')
)

status_choice = (
    ('1', 'Publish'),
    ('0', 'Unpublished'),
)

level_choice = (
    ('1', 'Dangerouse'),
    ('2', 'Mid Range'),
    ('0', 'Normal'),
)


class Disease(models.Model):
    name = models.CharField(max_length=500, null=False)
    found = models.CharField(max_length=1, choices=found_choice, null=True)
    summary = models.CharField(max_length=500, null=False)
    created_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=1, choices=status_choice, null=True)
    level = models.CharField(max_length=1, choices=level_choice, null=True)
    doctor = models.ManyToManyField(Doctor)

    def publish(self):
        self.status = 1
        self.save()

    def __str__(self):
        return self.name+"-"+self.found

    def get_absolute_url(self):
        return reverse('dashboard:diseases')

backend/hospital/doctor/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

# Create your models here.

status_choice = (
    ('1', 'Publish'),
    ('0', 'Unpublished'),
)

class Type(models.Model):
    name = models.CharField(max_length=500, null=False, blank=False)
    created_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=1, choices=status_choice, null=True)
    soft = models.BooleanField(default=1)
    counter = models.CharField(max_length=1000, default=0, null=True, blank=True)

    def __str__(self):
        return self.name

class Service(models.Model):
    name = models.CharField(max_length=500, null=False, blank=False)
    price = models.CharField(max_length=500, null=False, blank=False)
    status = models.BooleanField(default=0)
    soft = models.BooleanField(default=1)

    def __str__(self):
        return self.name

        
class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, null=True)
    image = models.FileField(verbose_name="Doctor Image")
    type = models.ManyToManyField(Type)
    service = models.ManyToManyField(Service)
    age = models.CharField(max_length=200, null=False)
    phone1 = models.CharField(max_length=800, null=False)
    phone2 = models.CharField(max_length=800, null=True)
    address = models.CharField(max_length=1000, null=True)
    statement = models.CharField(max_length=5000, null=False)
    educationStatement = models.CharField(max_length=5000, null=False)
    status = models.CharField(max_length=1, choices=status_choice, null=True)
    soft = models.BooleanField(default=1)
    views = models.CharField(max_length=5000, null=True, blank=True, default=0)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('dashboard:profile-save')

confirm_choice = (
    ('1', 'Confirmed'),
    ('0', 'Unconfirmed'),
)

checked_choice = (
    ('1', 'Checked'),
    ('0', 'Unchecked'),
)

payment_choice = (
    ('1', 'Paid'),
    ('0', 'Unpaid'),
)

source_choice = (
    ('1', 'Cash'),
    ('2', 'Credit Card'),
    ('3', 'Master Card')
)


class Booking(models.Model):
    service = models.CharField(max_length = 500, null = False, blank = False)
    doctor = models.ManyToManyField(Doctor)
    fn = models.CharField(max_length = 100, null = False, blank = False)
    ln = models.CharField(max_length = 100, null = False, blank = False)
    email = models.CharField(max_length = 500, null = True, blank = True)
    phone = models.CharField(max_length = 800, null = False, blank = False)
    location = models.CharField(max_length=300, null = False, blank = False)
    street1 = models.CharField(max_length=200, null = False, blank = False)
    street2 = models.CharField(max_length=200, null = True, blank = True)
    city = models.CharField(max_length=200, null = False, blank = False)
    state = models.CharField(max_length=100, null = True, blank = True)
    postal = models.CharField(max_length=100, null = True, blank = True)
    confirm = models.CharField(max_length=1, choices=confirm_choice, default = "0",null=False, blank = False)
    checked = models.CharField(max_length=1, choices=checked_choice, default = "0",null=False, blank = False)
    treatment = models.CharField(max_length=1000, null = True, blank = True)
    next  = models.CharField(max_length=1000, null = True, blank = True)
    note = models.CharField(max_length=1000, null = True, blank = True)
    created_at = models.DateTimeField(default=timezone.now)
    payment = models.CharField(max_length=1, choices=payment_choice, default = "0",null=False, blank = False)
    date = models.CharField(max_length=500, null=False, blank=False, default = "0")
    time = models.CharField(max_length=1000, null=False, blank=False, default = "0")
    amount = models.CharField(max_length = 10000, null=False, blank=False, default = "0")
    source = models.CharField(max_length=1, choices=source_choice, default = "0",null=False, blank = False)
    def __str__(self):
        return self.fn+" "+self.ln

class Review(models.Model):
    rate = models.CharField(max_length=100,null=False, blank=False)
    doctor = models.ManyToManyField(Doctor)
    title = models.CharField(max_length=500, null=False, blank=False)
    rev   = models.CharField(max_length=1000, null=False, blank=False)
    status = models.CharField(max_length=1, choices=status_choice, null=True, default=0)
    name = models.CharField(max_length=10000, null=False, blank=False, default="Anonymous")
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.title

backend/hospital/front/models.py
from django.db import models

# Create your models here.

backend/hospital/doctor/forms.py
from django import forms

class DoctorForm(forms.Form):
    name = forms.CharField()

backend/hospital/doctor/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class DoctorView(TemplateView):
    template_name = "doctor/index.html"

    def post(self, request):
        form = DoctorForm(request.POST)
        text = form.cleaned_data['name']

backend/hospital/front/views.py
from django.shortcuts import render,get_object_or_404
from disease.models import Disease, Doctor
from doctor.models import Service, Doctor, Booking, Type, Review
from blogs.models import Blogs
from django.db.models import Q
from company.models import Company
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.http import HttpResponseRedirect




def index(request):
    diseases = Disease.objects.filter(status="1")
    news = Blogs.objects.filter(status="1", types="1")[:10]
    events = Blogs.objects.filter(status="1", types="0")[:10]
    doctors = Doctor.objects.filter(status="1")
    company = Company.objects.all()
    t = Type.objects.order_by("-counter").all()[0]
    return render(request, 'front/index.html', {"t":t,"diseases":diseases,"news":news, "events":events, "doctors":doctors, "company":company})

def recommend(request, id):
    doctor = Doctor.objects.filter(type__id=id)
    return render(request, "front/detail/doctorsList.html", {"doctor":doctor})


def search(request):
    doctor = Doctor.objects.filter(name__istartswith=request.POST['name'])[0]
    if doctor:
        return render(request, "front/detail/doctor.html", {'doctor': doctor})
    else:
        return render(request, "front/detail/doctor.html", {'doctor': doctor})


def doctor(request, pk):
    doctor = get_object_or_404(Doctor, pk=pk)
    return render(request, "front/detail/doctor.html", {'doctor': doctor})


def news(request, pk):
    news = get_object_or_404(Blogs, pk=pk)
    news_more = Blogs.objects.filter(status=1, types=1).exclude(pk=pk)
    return render(request, "front/detail/news.html", {'news': news, 'news_more':news_more})


def events(request, pk):
    events = get_object_or_404(Blogs, pk=pk)
    events_more = Blogs.objects.filter(status=1, types=0).exclude(pk=pk)
    return render(request, "front/detail/events.html", {'events': events, 'events_more':events_more})


def list(request):
    doctor = Doctor.objects.filter(status=1).order_by("-id")
    return render(request, "front/detail/doctorsList.html", {'doctor': doctor})


def disease(request, pk):
    disease = Disease.objects.get(pk=pk)
    disease_name = disease.name
    blogs = Blogs.objects.filter(title__istartswith=disease_name)
    return render(request, "front/detail/disease.html", {"disease":disease,"blogs":blogs})
    
    
def booking(request):
    date = request.POST["dated"]
    time = request.POST["timed"]
    dr = Doctor.objects.filter(pk=request.POST["doctor"])[0]
    services = Service.objects.filter(pk__in=request.POST.getlist('visit'))
    total=0
    for i in services:
        total+=int(i.price)
    return render(request, "front/booking/booking.html", {"date":date, "time": time,"total":total, "dr":dr,"services":services})


def bookingConfirm(request):
    fn = request.POST['fn']
    ln = request.POST['ln']
    email = request.POST['email']
    phone = request.POST['phone']
    location = request.POST['location']
    street1  = request.POST['street1']
    street2  = request.POST['street2']
    a = request.POST.getlist('service')
    services = ', '.join(a)
    dr = request.POST['doctor']
    city  = request.POST['city']
    state  = request.POST['state']
    postal  = request.POST['postal']


    book = Booking.objects.create(service=services,fn=fn,ln=ln,email=email,phone=phone,location=location,street1=street1,street2=street2,city=city, state=state, postal=postal)
    book.save()

    doc = Doctor.objects.get(pk=dr)
    a= doc.type.all()[0]
    t = Type.objects.filter(id=a.id)[0]
    t.counter = str(int(t.counter)+1)
    t.save()
    book.doctor.add(doc)
    return render(request,"front/booking/confirm.html",{"a":t})


def review(request, id):
    if request.method == 'POST':
        rate = request.POST.get('rate')
        title = request.POST['title']
        re = request.POST['re']
        doc = Doctor.objects.filter(id=id)[0]
        review = Review.objects.create(rate=rate,title=title,rev=re)
        review.save()
        review.doctor.add(doc)
        messages.success(request, "Review send. It will be published once the doctor accepts it.")
        return HttpResponseRedirect('/doctor/%d' % int(id))
    else:
        doctor = Doctor.objects.filter(id=id)[0]
        return render(request, "front/detail/review.html", {"doctor":doctor})    


def blogs(request):
    news = Blogs.objects.filter(status=1, types=1)[:3]
    events = Blogs.objects.filter(status=1, types=0)[:3]
    return render(request, "front/detail/blogs.html", {'news': news, 'events':events})


def all_news(request):
    news = Blogs.objects.filter(status=1, types=1)
    return render(request, "front/detail/allnews.html", {"news":news})

def all_events(request):
    events = Blogs.objects.filter(status=1, types=0)
    return render(request, "front/detail/allevent.html", {"events":events})


def about(request):
    return render(request, "front/detail/about.html")

backend/hospital/front/templates/front/detail/blogs.html
{% extends "front/master.html" %}
{% block content %}
<main>
		<div id="breadcrumb">
			<div class="container">
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Category</a></li>
					<li>Page active</li>
				</ul>
			</div>
		</div>
		<!-- /breadcrumb -->
		<div class="container margin_60">
			<div class="main_title">
				<h1>Our events</h1>
			</div>
			<div class="row">
				<div class="col-md-12">
                    <article class="blog wow bounce">
                        <div class="row ">

                        {% for e in events %}
                            <div class="col-md-4">
                                <figure>
                                    <a href="{{ e.image.url }}" target="_blank"><img src="{{ e.image.url }}"  alt=""><div class="preview"></div></a>
                                </figure>
                            </div>
                            <div class="col-lg-8">
                                <div class="post_info">
                                    <small>{{ e.created_at }}</small>
                                    <h3><a href="{{e.image.url}}">{{ e.title }}</a></h3>
                                    <p>{{ e.intro }}</p>
                                    {% comment %} <ul>
                                        <li>
                                            <div class="thumb"><img src="../findoctor/img/thumb_blog.jpg" alt=""></div> Jessica Hoops
                                        </li>
                                        <li><i class="icon_comment_alt"></i> 20</li>
                                    </ul> {% endcomment %}
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    </article>
					<!-- /article -->
				</div>
			</div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <a href="{% url 'front:all_events' %}">
                    <button class="col-md-12 btn btn-primary">List All Events</button>
                    </a>
                </div>
            </div>
			<!-- /row -->
		</div>
        <div class="container margin_60">
			<div class="main_title">
				<h1>Our News</h1>
			</div>
			<div class="row">
				<div class="col-md-12">
                    <article class="blog wow bounce">
                        <div class="row ">

                        {% for e in news %}
                            <div class="col-md-4">
                                <figure>
                                    <a href="{{ e.image.url }}" target="_blank"><img src="{{ e.image.url }}"  alt=""><div class="preview"></div></a>
                                </figure>
                            </div>
                            <div class="col-lg-8">
                                <div class="post_info">
                                    <small>{{ e.created_at }}</small>
                                    <h3><a href="{{e.image.url}}">{{ e.title }}</a></h3>
                                    <p>{{ e.intro }}</p>
                                    {% comment %} <ul>
                                        <li>
                                            <div class="thumb"><img src="../findoctor/img/thumb_blog.jpg" alt=""></div> Jessica Hoops
                                        </li>
                                        <li><i class="icon_comment_alt"></i> 20</li>
                                    </ul> {% endcomment %}
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    </article>
					<!-- /article -->
				</div>
			</div>
             <div class="row">
                <div class="col-md-12">
<a href="{% url 'front:all_news' %}">
                    <button class="col-md-12 btn btn-primary">List All News</button>
                </a>
                </div>
            </div>
			<!-- /row -->
		</div>
	</main>
{% endblock  %}

backend/hospital/front/templates/front/detail/doctor.html
{% extends 'front/master.html' %}
{% block content %}
<main>
		<div id="breadcrumb">
			<div class="container">
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Category</a></li>
					<li>Page active</li>
				</ul>
			</div>
		</div>
		<!-- /breadcrumb -->
		{% if messages %}
		<div class="alert alert-success">
			
			{% for msg in messages %}
				{{msg}}
			{% endfor %}
		</div>
		{%endif%}
		<div class="container margin_60">
			<div class="row">
				<div class="col-xl-8 col-lg-8">
					<nav id="secondary_nav">
						<div class="container">
							<ul class="clearfix">
								<li><a href="#section_1" class="active">General info</a></li>
								<li><a href="#section_2">Reviews</a></li>
								<li><a href="#sidebar">Booking</a></li>
							</ul>
						</div>
					</nav>
					<div id="section_1">
						<div class="box_general_3">
							<div class="profile">
								<div class="row">
									<div class="col-lg-5 col-md-4">
										<figure>
											<img src="{{doctor.image.url}}" alt="" class="img-fluid">
										</figure>
									</div>
									<div class="col-lg-7 col-md-8">
										<small>
                                        {% for type in doctor.type.all %}
    										{{type}}
									    {%endfor%}
                                        </small>
										<h1>DR. {{doctor.name}}</h1>
										<span class="rating">
											<i class="icon_star voted"></i>
											<i class="icon_star voted"></i>
											<i class="icon_star voted"></i>
											<i class="icon_star voted"></i>
											<i class="icon_star"></i>
											<small>(145)</small>
											<a href="../findoctor/badges.html" data-toggle="tooltip" data-placement="top" data-original-title="Badge Level" class="badge_list_1"><img src="../findoctor/img/badges/badge_1.svg" width="15" height="15" alt=""></a>
										</span>
										<ul class="statistic">
											<li>854 Views</li>
											<li>124 Patients</li>
										</ul>
										<ul class="contacts">
											<li>
												<h6>Address</h6>
												{{doctor.address}} -
												<a href="https://www.google.com/maps/dir//Assistance+%E2%80%93+H%C3%B4pitaux+De+Paris,+3+Avenue+Victoria,+75004+Paris,+Francia/@48.8606548,2.3348734,14z/data=!4m15!1m6!3m5!1s0x0:0xa6a9af76b1e2d899!2sAssistance+%E2%80%93+H%C3%B4pitaux+De+Paris!8m2!3d48.8568376!4d2.3504305!4m7!1m0!1m5!1m1!1s0x47e67031f8c20147:0xa6a9af76b1e2d899!2m2!1d2.3504327!2d48.8568361" target="_blank"> <strong>View on map</strong></a>
											</li>
											<li>
												<h6>Phone:</h6> <a href="tel:{{ doctor.phone1 }}">{{ doctor.phone1 }}</a> - <a href="tel:{{doctor.phone2}}">{{ doctor.phone2 }}</a></li>
										</ul>
									</div>
								</div>
							</div>
							<hr>
							<!-- /profile -->
							<div class="indent_title_in">
								<i class="pe-7s-user"></i>
								<h3>Professional statement</h3>
								<p>Mussum ipsum cacilds, vidis litro abertis.</p>
							</div>
							<div class="wrapper_indent">
								<p>{{doctor.statement}}</p>
								<h6>Specializations</h6>
								<div class="row">
									<div class="col-lg-6">
										<ul class="bullets">
											<li>Abdominal Radiology</li>
											<li>Addiction Psychiatry</li>
											<li>Adolescent Medicine</li>
											<li>Cardiothoracic Radiology </li>
										</ul>
									</div>
									<div class="col-lg-6">
										<ul class="bullets">
											<li>Abdominal Radiology</li>
											<li>Addiction Psychiatry</li>
											<li>Adolescent Medicine</li>
											<li>Cardiothoracic Radiology </li>
										</ul>
									</div>
								</div>
								<!-- /row-->
							</div>
							<!-- /wrapper indent -->
							<hr>
							<div class="indent_title_in">
								<i class="pe-7s-news-paper"></i>
								<h3>Education</h3>
								<p>Mussum ipsum cacilds, vidis litro abertis.</p>
							</div>
							<div class="wrapper_indent">
								<p>{{doctor.educationStatement}}</p>
								<h6>Curriculum</h6>
								<ul class="list_edu">
									<li><strong>New York Medical College</strong> - Doctor of Medicine</li>
									<li><strong>Montefiore Medical Center</strong> - Residency in Internal Medicine</li>
									<li><strong>New York Medical College</strong> - Master Internal Medicine</li>
								</ul>
							</div>
							<!--  End wrapper indent -->
							<hr>
							<div class="indent_title_in">
								<i class="pe-7s-cash"></i>
								<h3>Prices & Payments</h3>
								<p>Mussum ipsum cacilds, vidis litro abertis.</p>
							</div>
							<div class="wrapper_indent">
								<p>Zril causae ancillae sit ea. Dicam veritus mediocritatem sea ex, nec id agam eius. Te pri facete latine salutandi, scripta mediocrem et sed, cum ne mundi vulputate. Ne his sint graeco detraxit, posse exerci volutpat has in.</p>
								<div class="table-responsive">
								<table class="table table-striped">
									<thead>
										<tr>
											<th>Service - Visit</th>
											<th>Price</th>
										</tr>
									</thead>
                                    <tbody>
                                        {% for service in doctor.service.all %}
                                            <tr>
                                                <td>{{service.name}}</td>
                                                <td>{{service.price}}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
								</table>
								</div>
							</div>
							<!--  /wrapper_indent -->
						</div>
						<!-- /section_1 -->
					</div>
					<!-- /box_general -->
					<div id="section_2">
						<div class="box_general_3">
							<div class="reviews-container">
								<div class="row">
									<div class="col-lg-3">
										<div id="review_summary">
											<strong>4.7</strong>
											<div class="rating">
												<i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i>
											</div>
											<small>Based on 4 reviews</small>
										</div>
									</div>
									<div class="col-lg-9">
										<div class="row">
											<div class="col-lg-10 col-9">
												<div class="progress">
													<div class="progress-bar" role="progressbar" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
												</div>
											</div>
											<div class="col-lg-2 col-3"><small><strong>5 stars</strong></small></div>
										</div>
										<!-- /row -->
										<div class="row">
											<div class="col-lg-10 col-9">
												<div class="progress">
													<div class="progress-bar" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
												</div>
											</div>
											<div class="col-lg-2 col-3"><small><strong>4 stars</strong></small></div>
										</div>
										<!-- /row -->
										<div class="row">
											<div class="col-lg-10 col-9">
												<div class="progress">
													<div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
												</div>
											</div>
											<div class="col-lg-2 col-3"><small><strong>3 stars</strong></small></div>
										</div>
										<!-- /row -->
										<div class="row">
											<div class="col-lg-10 col-9">
												<div class="progress">
													<div class="progress-bar" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
												</div>
											</div>
											<div class="col-lg-2 col-3"><small><strong>2 stars</strong></small></div>
										</div>
										<!-- /row -->
										<div class="row">
											<div class="col-lg-10 col-9">
												<div class="progress">
													<div class="progress-bar" role="progressbar" style="width: 0" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
												</div>
											</div>
											<div class="col-lg-2 col-3"><small><strong>1 stars</strong></small></div>
										</div>
										<!-- /row -->
									</div>
								</div>
								<!-- /row -->
								<hr>
								<div class="review-box clearfix">
									<figure class="rev-thumb"><img src="../findoctor/img/avatar1.jpg" alt="">
									</figure>
									<div class="rev-content">
										<div class="rating">
											<i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i>
										</div>
										<div class="rev-info">
											Admin – April 03, 2016:
										</div>
										<div class="rev-text">
											<p>
												Sed eget turpis a pede tempor malesuada. Vivamus quis mi at leo pulvinar hendrerit. Cum sociis natoque penatibus et magnis dis
											</p>
										</div>
									</div>
								</div>
								<!-- End review-box -->
								<div class="review-box clearfix">
									<figure class="rev-thumb"><img src="../findoctor/img/avatar2.jpg" alt="">
									</figure>
									<div class="rev-content">
										<div class="rating">
											<i class="icon-star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i>
										</div>
										<div class="rev-info">
											Ahsan – April 01, 2016
										</div>
										<div class="rev-text">
											<p>
												Sed eget turpis a pede tempor malesuada. Vivamus quis mi at leo pulvinar hendrerit. Cum sociis natoque penatibus et magnis dis
											</p>
										</div>
									</div>
								</div>
								<!-- End review-box -->
								<div class="review-box clearfix">
									<figure class="rev-thumb"><img src="../findoctor/img/avatar3.jpg" alt="">
									</figure>
									<div class="rev-content">
										<div class="rating">
											<i class="icon-star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i>
										</div>
										<div class="rev-info">
											Sara – March 31, 2016
										</div>
										<div class="rev-text">
											<p>
												Sed eget turpis a pede tempor malesuada. Vivamus quis mi at leo pulvinar hendrerit. Cum sociis natoque penatibus et magnis dis
											</p>
										</div>
									</div>
								</div>
								<!-- End review-box -->
							</div>
							<!-- End review-container -->
							<hr>
							<div class="text-right"><a href="{% url 'front:review' doctor.id %}" class="btn_1">Submit review</a></div>
						</div>
					</div>
					<!-- /section_2 -->
				</div>
				<!-- /col -->
				<aside class="col-xl-4 col-lg-4" id="sidebar">
					<div class="box_general_3 booking">
						<form action = "{% url 'front:booking' %}" method="POST">
						{% csrf_token %}
							<div class="title">
							<input type="hidden" name="doctor" value="{{doctor.pk}}"/>
							<h3>Book a Visit</h3>
							<small>Monday to Friday 09.00am-06.00pm</small>
							</div>
							<div class="row">
								<div class="col-6">
									<div class="form-group">
										<input class="form-control" type="text" id="booking_date" name="dated" data-lang="en" data-min-year="2017" data-max-year="2020" data-disabled-days="10/17/2017,11/18/2017">
									</div>
								</div>
								<div class="col-6">
									<div class="form-group">
										<input class="form-control" type="text" id="booking_time" name="timed" value="9:00 am">
									</div>
								</div>
							</div>
							<ul class="treatments clearfix">
								{% for service in doctor.service.all %}
                                    <li>
                                        <div class="checkbox">
                                            <input type="checkbox" class="css-checkbox" id="visit{{forloop.counter}}" name="visit" value="{{ service.id }}">
                                            <label for="visit{{forloop.counter}}" class="css-label">{{ service.name }}<strong>{{ service.price }}</strong></label>
                                        </div>
                                    </li>
                                {% endfor %}
							</ul>
							<input type="hidden" value="{{ doctor.id }}" name="docId"/>
							<hr>
							<button type="submit" class="btn_1 full-width">Book Now</button>
						</form>
					</div>
					<!-- /box_general -->
				</aside>
				<!-- /asdide -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</main>
{% endblock  %}