backend/hospital/front/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = "front"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('doctor/<int:pk>/', views.doctor, name='doctor'),
    path('disease/<int:pk>/', views.disease, name='disease'),
    path('doctor/book/', views.booking, name='booking'),
    path('doctor/lists/', views.list, name='list'),
    path('news/<int:pk>/', views.news, name='news'),
    path('events/<int:pk>/', views.events, name='events'),
    path('doctor/book/confirm', views.bookingConfirm, name="bookingConfirm"),
    path('doctor/recomment/<int:id>', views.recommend, name="recommend"),
    path("doctor/<int:id>/review",views.review, name="review"),
    path("news-and-events/", views.blogs, name="blogs"),
    path("news/", views.all_news, name="all_news"),
    path("events/", views.all_events, name="all_events"),
    path("about-us/", views.about, name="about")
]

backend/hospital/hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('front.urls')),
    path('dashboard/', admin.site.urls),
    path('doc/',include('doctor.urls')),
    path('admin/', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/hospital/front/models.py
from django.db import models

# Create your models here.

backend/hospital/front/views.py
from django.shortcuts import render,get_object_or_404
from disease.models import Disease, Doctor
from doctor.models import Service, Doctor, Booking, Type, Review
from blogs.models import Blogs
from django.db.models import Q
from company.models import Company
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.http import HttpResponseRedirect




def index(request):
    diseases = Disease.objects.filter(status="1")
    news = Blogs.objects.filter(status="1", types="1")[:10]
    events = Blogs.objects.filter(status="1", types="0")[:10]
    doctors = Doctor.objects.filter(status="1")
    company = Company.objects.all()
    t = Type.objects.order_by("-counter").all()[0]
    return render(request, 'front/index.html', {"t":t,"diseases":diseases,"news":news, "events":events, "doctors":doctors, "company":company})

def recommend(request, id):
    doctor = Doctor.objects.filter(type__id=id)
    return render(request, "front/detail/doctorsList.html", {"doctor":doctor})


def search(request):
    doctor = Doctor.objects.filter(name__istartswith=request.POST['name'])[0]
    if doctor:
        return render(request, "front/detail/doctor.html", {'doctor': doctor})
    else:
        return render(request, "front/detail/doctor.html", {'doctor': doctor})


def doctor(request, pk):
    doctor = get_object_or_404(Doctor, pk=pk)
    return render(request, "front/detail/doctor.html", {'doctor': doctor})


def news(request, pk):
    news = get_object_or_404(Blogs, pk=pk)
    news_more = Blogs.objects.filter(status=1, types=1).exclude(pk=pk)
    return render(request, "front/detail/news.html", {'news': news, 'news_more':news_more})


def events(request, pk):
    events = get_object_or_404(Blogs, pk=pk)
    events_more = Blogs.objects.filter(status=1, types=0).exclude(pk=pk)
    return render(request, "front/detail/events.html", {'events': events, 'events_more':events_more})


def list(request):
    doctor = Doctor.objects.filter(status=1).order_by("-id")
    return render(request, "front/detail/doctorsList.html", {'doctor': doctor})


def disease(request, pk):
    disease = Disease.objects.get(pk=pk)
    disease_name = disease.name
    blogs = Blogs.objects.filter(title__istartswith=disease_name)
    return render(request, "front/detail/disease.html", {"disease":disease,"blogs":blogs})
    
    
def booking(request):
    date = request.POST["dated"]
    time = request.POST["timed"]
    dr = Doctor.objects.filter(pk=request.POST["doctor"])[0]
    services = Service.objects.filter(pk__in=request.POST.getlist('visit'))
    total=0
    for i in services:
        total+=int(i.price)
    return render(request, "front/booking/booking.html", {"date":date, "time": time,"total":total, "dr":dr,"services":services})


def bookingConfirm(request):
    fn = request.POST['fn']
    ln = request.POST['ln']
    email = request.POST['email']
    phone = request.POST['phone']
    location = request.POST['location']
    street1  = request.POST['street1']
    street2  = request.POST['street2']
    a = request.POST.getlist('service')
    services = ', '.join(a)
    dr = request.POST['doctor']
    city  = request.POST['city']
    state  = request.POST['state']
    postal  = request.POST['postal']


    book = Booking.objects.create(service=services,fn=fn,ln=ln,email=email,phone=phone,location=location,street1=street1,street2=street2,city=city, state=state, postal=postal)
    book.save()

    doc = Doctor.objects.get(pk=dr)
    a= doc.type.all()[0]
    t = Type.objects.filter(id=a.id)[0]
    t.counter = str(int(t.counter)+1)
    t.save()
    book.doctor.add(doc)
    return render(request,"front/booking/confirm.html",{"a":t})


def review(request, id):
    if request.method == 'POST':
        rate = request.POST.get('rate')
        title = request.POST['title']
        re = request.POST['re']
        doc = Doctor.objects.filter(id=id)[0]
        review = Review.objects.create(rate=rate,title=title,rev=re)
        review.save()
        review.doctor.add(doc)
        messages.success(request, "Review send. It will be published once the doctor accepts it.")
        return HttpResponseRedirect('/doctor/%d' % int(id))
    else:
        doctor = Doctor.objects.filter(id=id)[0]
        return render(request, "front/detail/review.html", {"doctor":doctor})    


def blogs(request):
    news = Blogs.objects.filter(status=1, types=1)[:3]
    events = Blogs.objects.filter(status=1, types=0)[:3]
    return render(request, "front/detail/blogs.html", {'news': news, 'events':events})


def all_news(request):
    news = Blogs.objects.filter(status=1, types=1)
    return render(request, "front/detail/allnews.html", {"news":news})

def all_events(request):
    events = Blogs.objects.filter(status=1, types=0)
    return render(request, "front/detail/allevent.html", {"events":events})


def about(request):
    return render(request, "front/detail/about.html")

backend/hospital/front/templates/front/partials/footer.html
<footer  class="wow fadeInUp">
		<div class="container margin_60_35">
			<div class="row">
				<div class="col-lg-3 col-md-12">
					<p>
						<a href="../findoctor/index.html" title="Findoctor">
							<img src="../findoctor/img/logo.png" data-retina="true" alt="" width="163" height="36" class="img-fluid">
						</a>
					</p>
				</div>
				<div class="col-lg-3 col-md-4">
					<h5>About</h5>
					<ul class="links">
						<li><a href="#0">About us</a></li>
						<li><a href="../index.html">Blog</a></li>
						<li><a href="#0">FAQ</a></li>
						<li><a href="../findoctor/login.html">Login</a></li>
						<li><a href="../findoctor/register.html">Register</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-4">
					<h5>Useful links</h5>
					<ul class="links">
						<li><a href="#0">Doctors</a></li>
						<li><a href="#0">Clinics</a></li>
						<li><a href="#0">Specialization</a></li>
						<li><a href="#0">Join as a Doctor</a></li>
						<li><a href="#0">Download App</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-4">
					<h5>Contact with Us</h5>
					<ul class="contacts">
						<li><a href="tel://61280932400"><i class="icon_mobile"></i> + 61 23 8093 3400</a></li>
						<li><a href="mailto:info@findoctor.com"><i class="icon_mail_alt"></i> help@findoctor.com</a></li>
					</ul>
					<div class="follow_us">
						<h5>Follow us</h5>
						<ul>
							<li><a href="#0"><i class="social_facebook"></i></a></li>
							<li><a href="#0"><i class="social_twitter"></i></a></li>
							<li><a href="#0"><i class="social_linkedin"></i></a></li>
							<li><a href="#0"><i class="social_instagram"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<!--/row-->
			<hr>
			<div class="row">
				<div class="col-md-8">
					<ul id="additional_links">
						<li><a href="#0">Terms and conditions</a></li>
						<li><a href="#0">Privacy</a></li>
					</ul>
				</div>
				<div class="col-md-4">
					<div id="copy">© 2019 {% block company_name %} {% endblock %}</div>
				</div>
			</div>
		</div>
	</footer>
	<!--/footer-->
	</div>
	<!-- page -->
	<div id="toTop"></div>
	<!-- Back to top button -->
	<!-- COMMON SCRIPTS -->
	{% load staticfiles %}
	<script src="{% static 'frontend/js/jquery-2.2.4.min.js' %}"></script>
	<script src="{% static 'frontend/js/common_scripts.min.js' %}"></script>
	<script src="{% static 'frontend/js/functions.js' %}"></script>
	<script src="{% static 'frontend/js/jquery.cookiebar.js' %}"></script>
	<script>
		$(document).ready(function(){
		'use strict';
		 $.cookieBar({
			fixed: true
		});
		});
	</script>
</body>
</html>

backend/hospital/front/templates/front/partials/header.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load staticfiles %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Find easily a doctor and book online an appointment">
	<meta name="author" content="Ansonika">
	<title>FINDOCTOR - Find easily a doctor and book online an appointment</title>
	<!-- Favicons-->
	<link rel="shortcut icon" href="{% static 'frontend/img/favicon.ico'%}" type="image/x-icon">
	<link rel="apple-touch-icon" type="image/x-icon" href="{% static 'frontend/img/apple-touch-icon-57x57-precomposed.png' %}">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{% static 'frontend/img/apple-touch-icon-72x72-precomposed.png' %}">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="{% static 'frontend/img/apple-touch-icon-114x114-precomposed.png' %}">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="{% static 'frontend/img/apple-touch-icon-144x144-precomposed.png' %}">
	<!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800" rel="stylesheet">
	<!-- BASE CSS -->
	<link href='{% static "frontend/css/bootstrap.min.css" %}' rel="stylesheet">
	<link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'frontend/css/menu.css' %}" rel="stylesheet">
	<link href="{% static 'frontend/css/vendors.css' %}" rel="stylesheet">
	<link href="{% static 'frontend/css/icon_fonts/css/all_icons_min.css' %}" rel="stylesheet">
	<!-- YOUR CUSTOM CSS -->
    <link href="{% static 'frontend/css/blog.css'%}" rel="stylesheet">

	<link href="{% static 'frontend/css/custom.css' %}" rel="stylesheet">
	
</head>
<body>
	<div id="page">		

backend/hospital/front/templates/front/partials/navigation.html
<header class="header_sticky">	
		<a href="#menu" class="btn_mobile">
			<div class="hamburger hamburger--spin" id="hamburger">
				<div class="hamburger-box">
					<div class="hamburger-inner"></div>
				</div>
			</div>
		</a>
		<!-- /btn_mobile-->
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-6">
					<a href="/"><h3>Bio Hospital</h3></a>	
				</div>
				<div class="col-lg-9 col-6">
				
					<nav id="menu" class="main-menu">
						<ul>
							<li>
								<span><a href="/">Home</a></span>
							</li>
							<li>
								<span><a href="{% url 'front:list' %}">Doctors</a></span>
							</li>
							<li>
								<span><a href="{% url 'front:blogs' %}">News and Events</a></span>
							</li>
                            <li>
								<span><a href="{% url 'front:about' %}">About Us</a></span>
							</li>
							<li>
								<span><a href="{% url 'front:about' %}">Predictons</a></span>
							</li>
						</ul>
					</nav>
					<!-- /main-menu -->
				</div>
			</div>
		</div>
		<!-- /container -->
	</header>