backend/hospital/dashboard/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = "dashboard"

urlpatterns = [
    path('', views.IndexView, name="index"),
    path('accounts/', include('django.contrib.auth.urls')),


    path('doctor/register/', views.register, name="register"),

    url(r'users/$', views.UserView.as_view(), name="users"),
    # path('cancer/', views.CancerPredictions.as_view(), name="cancer"),
    url(r'users/create$', views.registerUser, name="user-create"),
    
    # # user detail view url dashboard/users/details/n
    # url(r'^users/details/(?P<pk>[0-9]+)/$', views.UserDetailView.as_view(), name="user-detail"),

    # user update view url dashboard/users/n
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserUpdate.as_view(), name="user-update"),

     # user update view url dashboard/users/n/delete
    url(r'^users/(?P<pk>[0-9]+)/delete$', views.UserDelete.as_view(), name="user-delete"),


    # Disease index view
    url(r'diseases/$', views.DiseaseView.as_view(), name="diseases"),
    url(r'diseases/create$', views.DiseaseCreate.as_view(), name="disease-create"),
    
    # disease update view url dashboard/disease/n
    url(r'^diseases/(?P<pk>[0-9]+)/$', views.DiseaseUpdate.as_view(), name="disease-update"),

     # disease update view url dashboard/disease/n/delete
    url(r'^diseases/(?P<pk>[0-9]+)/delete$', views.DiseaseDelete.as_view(), name="disease-delete"),

    url(r'^diseases/status/(?P<id>[0-9]+)/$', views.DiseaseStatus, name="disease-status"),


    # Blogs index view
    url(r'blogs/$', views.BlogView.as_view(), name="blogs"),
    url(r'blogs/create$', views.BlogCreate.as_view(), name="blog-create"),
    
    # Blogs update view url dashboard/blogs/n
    url(r'^blogs/(?P<pk>[0-9]+)/$', views.BlogUpdate.as_view(), name="blog-update"),

     # Blogs update view url dashboard/blogs/n/delete
    url(r'^blogs/(?P<pk>[0-9]+)/delete$', views.BlogDelete.as_view(), name="blog-delete"),

    url(r'^blogs/status/(?P<id>[0-9]+)/$', views.BlogStatus, name="blog-status"),

    # Blogs index view url dashboard/blogs/n
    url(r'^company/$', views.CompanyIndex, name="company-index"),

    # company view url dashboard/blogs/n
    url(r'^company/update/(?P<pk>[0-9]+)/$', views.CompanyDetailUpdate.as_view(), name="company-update"),


    path('doctors/', views.doctors.as_view(), name="doctors"),
    path('doctors/create-doctors', views.register, name="create-doctors"),

    path('appointments/',views.appointments, name="appointments"),
    path('confirm/<int:id>/', views.confirmation, name="confirm"),
    path('profile/',views.profile, name="profile"),
    path('profile/save/',views.profile,name="profile-save"),
    path('me-booked/',views.book,name="me-booked"),
    path('patient-details/<int:pk>/',views.patientDetails, name="patient-details"),
    path('checked-by-doctor/<int:id>/',views.checked, name="checked"),
    path('patient/submit-report/<int:id>/',views.submitReport, name="submitReport"),
    path('doctors/services/', views.services, name="services"),
    path('doctors/services/status/<int:id>/',views.serviceStatus, name="serviceStatus"),
    path('doctors/services/create/', views.createService, name="create-service"),
    path('doctors/review/', views.review, name="review"),
    path('doctors/review/details/<int:id>/', views.revDetail, name="review-details"),
    path("doctors/review/status/<int:id>/",views.reviewStatus, name="review-status"),
    path("doctors/review/delete/<int:id>/", views.reviewDelete, name="review-delete")

]

backend/hospital/front/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = "front"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('doctor/<int:pk>/', views.doctor, name='doctor'),
    path('disease/<int:pk>/', views.disease, name='disease'),
    path('doctor/book/', views.booking, name='booking'),
    path('doctor/lists/', views.list, name='list'),
    path('news/<int:pk>/', views.news, name='news'),
    path('events/<int:pk>/', views.events, name='events'),
    path('doctor/book/confirm', views.bookingConfirm, name="bookingConfirm"),
    path('doctor/recomment/<int:id>', views.recommend, name="recommend"),
    path("doctor/<int:id>/review",views.review, name="review"),
    path("news-and-events/", views.blogs, name="blogs"),
    path("news/", views.all_news, name="all_news"),
    path("events/", views.all_events, name="all_events"),
    path("about-us/", views.about, name="about")
]

backend/hospital/hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('front.urls')),
    path('dashboard/', admin.site.urls),
    path('doc/',include('doctor.urls')),
    path('admin/', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/hospital/dashboard/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from doctor.models import Doctor, Service

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username','email', 'password','is_staff','is_superuser']


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    is_staff = True
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        for fieldnames in ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']:
            self.fields[fieldnames].help_text = None
            self.fields[fieldnames].widget.attrs.update({'class': 'form-control autofocus'})

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2','is_staff','is_superuser')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ('name', 'image', 'age', 'phone1', 'phone2', 'address', 'statement','status','educationStatement','service','type')

        toppings = forms.ModelMultipleChoiceField(queryset=Service.objects.all())
        def __init__(self, *args, **kwargs):
            # Only in case we build the form from an instance
            # (otherwise, 'toppings' list should be empty)
            if kwargs.get('instance'):
                # We get the 'initial' keyword argument or initialize it
                # as a dict if it didn't exist.                
                initial = kwargs.setdefault('initial', {})
                # The widget for a ModelMultipleChoiceField expects
                # a list of primary key for the selected data.
                initial['toppings'] = [t.pk for t in kwargs['instance'].topping_set.all()]

            forms.ModelForm.__init__(self, *args, **kwargs)

backend/hospital/dashboard/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render
from players.models import Players, Role
from disease.models import Disease
from blogs.models import Blogs
from company.models import Company
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.views.generic import TemplateView, View
import _pickle as cPickle
import pickle
from .forms import UserForm, SignUpForm, ProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from django.utils.decorators import method_decorator
# Landing page /dashboard
from doctor.models import Doctor,Booking, Service, Type,Review
from xhtml2pdf import pisa

@login_required(login_url='/admin/accounts/login/')
def IndexView(request):
    return render(request,"dashboard/pages/index.html")



# User Landing page /dashboard/users
class UserView(generic.ListView):
    context_object_name = "users"

    template_name = "dashboard/pages/users/index.html"
   
    def get_queryset(self):
        return User.objects.filter(is_staff=1, is_superuser=0)


# User Create page /dashboard/users/create
class UserCreate(CreateView):
    model = Players
    fields = ['fn','ln','address','phone','email','password','username','image','role']

# User Update page /dashboard/users
class UserUpdate(UpdateView):
    model = Players
    fields = ['fn','ln','address','phone','email','password','username','image','role']

# User Delete page
class UserDelete(DeleteView):
    model = User
    success_url = reverse_lazy('dashboard:doctors')



# Disease Landing page /dashboard/users
class DiseaseView(generic.ListView):
    context_object_name = "diseases"
    template_name = "dashboard/pages/disease/index.html"
   
    def get_queryset(self):
        return Disease.objects.all()

# Disease Create page /dashboard/users/create
class DiseaseCreate(CreateView):
    model = Disease
    fields = ['name','found','summary','doctor','status','level']

# Disease Update page /dashboard/users
class DiseaseUpdate(UpdateView):
    model = Disease
    fields = ['name',' ','summary','doctor','status', 'level']

# Disease Delete page
class DiseaseDelete(DeleteView):
    model = Disease
    success_url = reverse_lazy('dashboard:diseases')


def DiseaseStatus(request, id):
    disease = get_object_or_404(Disease, id=id)
    status = disease.status
    
    if(status == "1"):
        disease.status = "0"
        messages.success(request, "Status unpublished successfully.", extra_tags="0")
    else:
        disease.status = "1"
        messages.success(request, "Status published successfully.", extra_tags="1")

    disease.save()
    return redirect("/admin/diseases/")



# Blogs Landing page /dashboard/users
class BlogView(generic.ListView):
    context_object_name = "blogs"
    template_name = "dashboard/pages/blogs/index.html"
   
    def get_queryset(self):
        return Blogs.objects.all()

# Blogs Create page /dashboard/users/create
class BlogCreate(CreateView):
    model = Blogs
    fields = ['title','intro','description','image','status','types']

# Blogs Update page /dashboard/users
class BlogUpdate(UpdateView):
    model = Blogs
    fields = ['title','intro','description','image','status']

# Blogs Delete page
class BlogDelete(DeleteView):
    model = Blogs
    success_url = reverse_lazy('dashboard:blogs')

def BlogStatus(request, id):
    blog = get_object_or_404(Blogs, id=id)
    status = blog.status
    
    if(status == "1"):
        blog.status = "0"
        messages.success(request, "Status unpublished successfully.", extra_tags="0")
    else:
        blog.status = "1"
        messages.success(request, "Status published successfully.", extra_tags="1")

    blog.save()
    return redirect("/admin/blogs/")

# Company Details
def CompanyIndex(request):
    company = Company.objects.all()[0]
    return render(request, "dashboard/pages/company/index.html", {"company":company})

# Company Detail Update
def a(request):
    name = request.get("name")
    company = Company.objects.all()
    company.name = name
    company.save()
    return redirect("/admin/company/")


# Disease Update page /dashboard/users
class CompanyDetailUpdate(UpdateView):
    model = Company
    fields = ['name','address','phone1','phone2','email','facebook','instagram','twitter','youtube','fax','pobox']


# class CancerPredictions(generic.ListView):
#     context_object_name = "users"
#     template_name = "dashboard/pages/cancer/index.html"
#     ml = pickle.load(open('/home/saijal/Desktop/model.pkl','rb'))
#     output['oo'] = ml.predict(50,205.40,656.3,545.44,65.500)
#     res = ml
#     def get_queryset(self):
#         return res

class UserFormView(View):
    form_class = UserForm
    template_name = 'dashboard/pages/registration_form.html'

    def get(self, request):
        form  = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form  = self.form_class(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.is_staff = True

            user = User(username=username)
            user.is_staff = True

            user.set_password(password)
            user.save()
            return render(request, "dashboard/pages/doctor/create.html", {'form':form})

        return render(request, self.template_name, {'form':form})


class doctors(generic.ListView):
    context_object_name = "doctors"

    template_name = "dashboard/pages/doctors/index.html"
   
    def get_queryset(self):
        return User.objects.filter(is_staff=1,is_superuser=1).exclude(username="admin")
    

def DoctorCreate(request):
    if request.method == "POST":
        pass
    else:
        return render(request, "dashboard/pages/doctors/create.html")
        
# @login_required(login_url='/admin/accounts/login/')
def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            user.is_staff = True
            user.is_superuser = True
            user.save()
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])

            return render(request, "dashboard/pages/doctors/create.html", context={"form": form})

    form = SignUpForm()
    return render(request, "dashboard/pages/doctors/create.html", {"form": form})


def registerUser(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            user.is_staff = True
            user.save()
            return redirect("/admin/users")
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])
            return render(request, "dashboard/pages/users/create.html", context={"form": form})

    form = SignUpForm()
    return render(request, "dashboard/pages/users/create.html", {"form": form})


def appointments(request):
    appointment = Booking.objects.order_by("confirm").all()
    return render(request, "dashboard/pages/doctors/appointment/index.html",{"appointment":appointment})

def confirmation(request, id):
    booking = get_object_or_404(Booking, id=id)
    
    if booking.confirm == "0":
        booking.confirm = "1"
        messages.success(request, "Booking is confirmed", extra_tags="1")
    else:
        booking.confirm = "0"
        messages.success(request, "Booking is unconfirmed", extra_tags="0")

    booking.save()
    return redirect("/admin/appointments/")

    
def profile(request):
    pk = request.user.id
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            post.user = request.user
            post.image = form.cleaned_data['image']
            post.save()
            cat = Type.objects.get(pk=request.POST['type'])
            post.type.add(cat)
            answer = form.cleaned_data['service']
            post.service.set(answer)
            return redirect('/admin/profile/')
    else:
        form = ProfileForm()
    args = {'profile': Doctor.objects.filter(user_id=pk).first(), 'form': form}
    return render(request, 'dashboard/pages/doctors/profile.html', args)    


class DocCreate(CreateView):
    model = Doctor
    fields = ['name','image','age','statement','status']


def book(request):
    doctor = Doctor.objects.filter(user_id=request.user.id)[0]
    book = Booking.objects.order_by("-confirm").filter(doctor__id=doctor.id, confirm=1)
    return render(request, "dashboard/pages/doctors/appointment/fordoctor.html",{"appointment":book})


def patientDetails(request, pk):
    booking = Booking.objects.filter(id=pk)[0]
    a = booking.service
    b = a.split(",")
    service = Service.objects.filter(id__in=b)
    return render(request, "dashboard/pages/doctors/appointment/patient.html",{"patient":booking,"service":service})


def checked(request, id):
    booking = get_object_or_404(Booking, id=id)
    
    if booking.checked == "0":
        booking.checked = "1"

backend/hospital/dashboard/templates/dashboard/pages/users/create.html
{% extends 'dashboard/main.html' %}
{%block content%}
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Add Staff Users
            <small>[All credentials]</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'dashboard:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{% url 'dashboard:users'%}">Users</a></li>
            <li class="active">Add</li>
          </ol>
        </section>
        <section class="content container-fluid">
        <div class="row">
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Login Information</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
              <div class="box-body">
                 <form role="form"  method="POST">
                  {% csrf_token %}
                   <div class="form-group">
                   {{ form.username.errors }}
                    <label class="col-sm-2 control-label" for="{{ form.username.id_for_label }}">Username </label>

                    <div class="col-sm-10">
                      {{ form.username }}
                    </div>
                  </div>
                  <br/>
                  <br/>
                  <br/>
                  <div class="form-group">
                  {{ form.first_name.errors }}
                    <label class="col-sm-2 control-label" for="{{ form.first_name.id_for_label }}">First Name </label>

                    <div class="col-sm-10">
                      {{ form.first_name }}
                    </div>
                  </div>
                  <br/>
                  <br/>
                  <div class="form-group">
                  {{ form.last_name.errors }}
                    <label class="col-sm-2 control-label" for="{{ form.last_name.id_for_label }}">Last Name </label>

                    <div class="col-sm-10">
                      {{ form.last_name }}
                    </div>
                  </div>
                    <br/>
                  <br/>
                  <div class="form-group">
                  {{ form.email.errors }}
                    <label class="col-sm-2 control-label" for="{{ form.email.id_for_label }}">Email </label>

                    <div class="col-sm-10">
                      {{ form.email }}
                    </div>
                  </div>
                  <br/>
                  <br/>
                  <div class="form-group">
                  {{ form.password1.errors }}
                    <label class="col-sm-2 control-label" for="{{ form.password1_myself.id_for_label }}">Password </label>
                    <div class="col-sm-10">
                      {{ form.password1 }}
                    </div>
                  </div>
                  <br/>
                  <br/>
                  <div class="form-group">
                  {{ form.password2.errors }}
                    <label class="col-sm-2 control-label" for="{{ form.password2_myself.id_for_label }}">Confirm Password </label>
                    <div class="col-sm-10">
                      {{ form.password2 }}
                    </div>
                  </div>
                   
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Submit</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
          <!-- /.box -->
        </div>
        <!--/.col (right) -->
      </div>
        </section>
</div>
{% endblock %}

backend/hospital/dashboard/templates/dashboard/pages/users/index.html
{% extends 'dashboard/main.html' %}
{%block content%}
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Users
            <small>[All Users]</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'dashboard:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Users</li>
          </ol>
        </section>
        <section class="content container-fluid">
            <div class="box">
                <div class="box-header" style="display:flex; flex-flow: row wrap;">
                  <h3 class="box-title">Data Table With Basic Info</h3>
                  <div class="as"> <a href="{% url 'dashboard:user-create' %}"> <button class="btn btn-success btn-sm" style="right:0%">+Add</button></a></div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                      <th>S.No.</th>
                      <th>Name</th>
                      <th>Option</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                      <tr>
                          <td>{{forloop.counter}}</td>
                          <td>{{user.username}}</td>
                          <td><a href="{% url 'dashboard:user-update' user.pk %}"><button class="btn btn-primary"><i class="fa fa-pencil" aria-hidden="true"></i></button></a>
                          <form action="{% url 'dashboard:user-delete' user.pk %}" method="post">
                          {% csrf_token %}
                            <button class="btn btn-danger" type="submit"><i class="fa fa-trash" aria-hidden="true"></i></button></td>
                          </form>
                      </tr>
                    {%endfor%}
                    
                    </tbody>
                  </table>
                </div>
                <!-- /.box-body -->
              </div>
            <ul>
                
            </ul>
        </section>
</div>
{% endblock %}